name: Check code examples on python3.8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  launch_height_baselines.py:
    runs-on: 
      labels: temporary-sizing-testing_ubuntu-latest_8-core
    steps:
    - uses: awslabs/syne-tune/.github/workflows/install-syne-tune.yml@main
    - name: Run examples/launch_height_baselines.py
      run: |
        python examples/launch_height_baselines.py

  launch_height_python_backend.py:
    runs-on: 
      labels: temporary-sizing-testing_ubuntu-latest_8-core
    steps:
    - uses: awslabs/syne-tune/.github/workflows/install-syne-tune.yml@main
    - name: Run examples/launch_height_python_backend.py
      run: |
        python examples/launch_height_python_backend.py
  
  # launch_height_moasha.py:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_height_moasha.py
  #     run: | 
  #       python examples/launch_height_moasha.py
  # launch_height_standalone_scheduler.py:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run launch_height_standalone_scheduler.py
  #     run: |
  #       python examples/launch_height_standalone_scheduler.py
  
  # launch_pbt.py:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_pbt.py
  #     run: |
  #       python examples/launch_pbt.py
    
  # launch_bayesopt_constrained.py:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_bayesopt_constrained.py
  #     run: |
  #       python examples/launch_bayesopt_constrained.py
    
  # launch_checkpoint_example.py:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_checkpoint_example.py
  #     run: |                   
  #       python examples/launch_checkpoint_example.py
    
  # launch_height_ray.py:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_height_ray.py
  #     run: |
  #       python examples/launch_height_ray.py
    
  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_huggingface_classification.py
  #     run: |
  #       python examples/launch_huggingface_classification.py


  #   # - name: 
  #   #   run: | python examples/launch_rl_tuning.py # TODO enable once fixed

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_fashionmnist.py
  #     run: |
  #       python examples/launch_fashionmnist.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_height_sagemaker.py
  #     run: |
  #       python examples/launch_height_sagemaker.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_moasha_instance_tuning.py
  #     run: |
  #       python examples/launch_moasha_instance_tuning.py
  
  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_simulated_benchmark.py
  #     run: |
  #       python examples/launch_simulated_benchmark.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_asha_yahpo.py
  #     run: |
  #       python examples/launch_asha_yahpo.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_fashionmnist_costaware.py
  #     run: |
  #       python examples/launch_fashionmnist_costaware.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_height_sagemaker_checkpoints.py
  #     run: |
  #       python examples/launch_height_sagemaker_checkpoints.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_nas201_transfer_learning.py
  #     run: |
  #       python examples/launch_nas201_transfer_learning.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_standalone_bayesian_optimization.py
  #     run: |
  #       python examples/launch_standalone_bayesian_optimization.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_ask_tell_scheduler.py
  #     run: |
  #       python examples/launch_ask_tell_scheduler.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_nasbench201_simulated.py
  #     run: |
  #       python examples/launch_nasbench201_simulated.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_tensorboard_example.py
  #     run: |
  #       python examples/launch_tensorboard_example.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_ask_tell_scheduler_hyperband.py
  #     run: |
  #       python examples/launch_ask_tell_scheduler_hyperband.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_height_sagemaker_remotely.py
  #     run: |
  #       python examples/launch_height_sagemaker_remotely.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_tuning_gluonts.py
  #     run: |
  #       python examples/launch_tuning_gluonts.py

  # build:
  #   runs-on: 
  #     labels: temporary-sizing-testing_ubuntu-latest_8-core
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -e '.[extra]'
  #   - name: Run examples/launch_plot_results.py
  #     run: |
  #       python examples/launch_plot_results.py
