name: Check code quality and examples on python3.8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install .[extra] --upgrade pip
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82,F401 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test examples
      run: |
        python examples/launch_height_baselines.py
        python examples/launch_height_python_backend.py
        python examples/launch_height_moasha.py
        python examples/launch_height_standalone_scheduler.py
        python examples/launch_pbt.py
        python examples/launch_bayesopt_constrained.py                        
        python examples/launch_checkpoint_example.py
        python examples/launch_height_ray.py
        python examples/launch_huggingface_classification.py
        # python examples/launch_rl_tuning.py # TODO enable once fixed
        python examples/launch_fashionmnist.py
        python examples/launch_height_sagemaker.py
        python examples/launch_moasha_instance_tuning.py
        python examples/launch_simulated_benchmark.py 
        python examples/launch_asha_yahpo.py
        python examples/launch_fashionmnist_costaware.py
        python examples/launch_height_sagemaker_checkpoints.py
        python examples/launch_nas201_transfer_learning.py
        python examples/launch_standalone_bayesian_optimization.py
        python examples/launch_ask_tell_scheduler.py
        # python examples/launch_height_sagemaker_custom_image.py
        python examples/launch_nasbench201_simulated.py
        python examples/launch_tensorboard_example.py
        python examples/launch_ask_tell_scheduler_hyperband.py
        python examples/launch_height_sagemaker_remotely.py
        python examples/launch_tuning_gluonts.py
        python examples/launch_plot_results.py
