name: Check code examples on python3.8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  launch_height_baselines:
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_height_baselines.py

  launch_height_python_backend:
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_height_python_backend.py
