name: End-to-end Tests

# TODO set this up to gate new releases of Syne Tune
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request: # remove before merging, this is for testing
    branches:   # remove before merging, this is for testing
      - main    # remove before merging, this is for testing


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_ROLE: ${{ secrets.PROD_AWS_INTEG_TEST_ROLE_ARN }}

jobs:
  stop_all_training_jobs: 
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PROD_AWS_INTEG_TEST_ROLE_ARN }}
          role-session-name: integtestsession
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Stop all left-over training jobs
        run: |
          aws sagemaker list-training-jobs --status-equals InProgress > running_jobs.json
          jq -c '.[][]["TrainingJobName"]' running_jobs.json | while read i; do
            jobName=`echo $i | cut -d "\"" -f 2`
            echo "stopping training job $jobName"
            aws sagemaker stop-training-job --training-job-name $jobName
            sleep 5
          done
  
  launch_tuning_gluonts:
    needs: stop_all_training_jobs
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_tuning_gluonts.py
      requires-aws-credentials: true
    secrets: inherit

  launch_moasha_instance_tuning:
    needs: stop_all_training_jobs
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_moasha_instance_tuning.py
      requires-aws-credentials: true
    secrets: inherit

  launch_height_sagemaker:
    needs: stop_all_training_jobs
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_height_sagemaker.py
      requires-aws-credentials: true
    secrets: inherit

  launch_huggingface_classification:
    needs: stop_all_training_jobs
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_huggingface_classification.py
      requires-aws-credentials: true
    secrets: inherit

  launch_height_sagemaker_remotely:
    needs: stop_all_training_jobs
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_height_sagemaker_remotely.py
      requires-aws-credentials: true
    secrets: inherit

  launch_height_sagemaker_checkpoints:
    needs: stop_all_training_jobs
    uses: ./.github/workflows/run-syne-tune.yml
    with:
      script-path: examples/launch_height_sagemaker_checkpoints.py
      requires-aws-credentials: true
    secrets: inherit
