name: Run Syne Tune Example

on:
  workflow_call:
    inputs:
      script-path:
        required: true
        type: string

jobs:
  run-syne-tune:
    runs-on:
      labels: temporary-sizing-testing_ubuntu-latest_8-core 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[extra]'
      - name: Run ${{ inputs.script-path }}
        run: |
          python -m ${{ inputs.script-path }}
