on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: 1.20
    - name: install git-chlog
      run: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
      env:
        GOPATH: $HOME/go
    - name: generate changelog
      run: git-chglog
