on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: generate changelog
      run: | 
        git fetch --tags origin
        CURRENT_VERSION=$(shell git describe --abbrev=0 --tag) ;\
        echo "[+] Pre-generating CHANGELOG for tag: $$CURRENT_VERSION" ;\
        docker run -v "${PWD}":/workdir quay.io/git-chglog/git-chglog:0.15.1
