on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: 1.15
    - name: install git-chlog
      run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
    - name: generate changelog
      run: git-chglog
