name: Update Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-changelog:
    concurrency:
      group: changelog-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      with:
        fetch-depth: 0
      uses: actions/checkout@v3
    - name: generate changelog
      run: | 
        git fetch --tags origin
        docker run -v "${PWD}":/workdir quay.io/git-chglog/git-chglog:0.15.4
