name: Update Changelog

on:
  workflow_dispatch:
    inputs:
      version_for_changelog:
        description: "Version to draft the changelog for, e.g. v0.7.0 or v0.12.3"
        required: true
  pull_request:
    branches:
      - main

jobs:
  update-changelog:
    concurrency:
      group: changelog-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      with:
        fetch-depth: 0
      uses: actions/checkout@v3
    - name: generate changelog
      run: | 
        git fetch --tags origin
        docker run -v "${PWD}":/workdir quay.io/git-chglog/git-chglog:0.15.4 ${{ inputs.version_for_changelog }}
